const { contextBridge, ipcRenderer } = require('electron')

const inv = (ch) => (...a) => ipcRenderer.invoke(ch, ...a)

contextBridge.exposeInMainWorld('folio', {
  openDialog: inv('file:open-dialog'),
  readFile: inv('file:read'),
  writeFile: inv('file:write'),
  saveDialog: inv('file:save-dialog'),
  openFolderDialog: inv('folder:open-dialog'),
  folderTree: inv('folder:tree'),
  reveal: inv('file:reveal'),
  createFile: inv('file:create'),
  renameFile: inv('file:rename'),
  trashFile: inv('file:trash'),
  searchFolder: inv('folder:search'),
  pathForFile: (f) => require('electron').webUtils.getPathForFile(f),
  stat: inv('file:stat'),
  getUpdateState: inv('update:get'),
  checkUpdates: inv('update:check'),
  downloadUpdate: inv('update:download'),
  installUpdate: inv('update:install'),
  openReleases: inv('update:releases'),
  onUpdateStatus: (cb) => ipcRenderer.on('update:status', (_e, s) => cb(s)),
  listUserThemes: inv('themes:list'),
  openThemesFolder: inv('themes:open-folder'),
  listPlugins: inv('plugins:list'),
  setPluginEnabled: inv('plugins:set-enabled'),
  openPluginsFolder: inv('plugins:open-folder'),
  readImage: inv('file:read-image'),
  saveImage: inv('file:save-image'),
  exportHtml: inv('export:html'),
  exportPdf: inv('export:pdf'),
  takePendingOpen: inv('app:take-pending-open'),
  setTitle: inv('app:set-title'),
  setThemeBg: inv('app:set-theme-bg'),
  confirm: inv('app:confirm'),
  devtools: inv('app:devtools'),
  onOpenPath: (cb) => ipcRenderer.on('open-path', (_e, p) => cb(p)),
})
